### ISSUE TITLE
Setting certain parameters in simulation causes crash

### ISSUE THREAD

**Issue by pjreiniger** [wpilibsuite/2025Beta#28]
**Describe the bug**
I might be missing something for the docs or am misinterpreting the new API, but it seems like when I try to set up a follower, the code crashes when running a simulation

**To Reproduce**
- Fresh CommandBased Template
- Update the auto generated subsystem
  ```

  public ExampleSubsystem() {
    SparkMax leader = new SparkMax(1, MotorType.kBrushless);
    SparkMax follower = new SparkMax(2, MotorType.kBrushless);
  
    SparkMaxConfig followerConfig = new SparkMaxConfig();
    followerConfig.follow(leader);
    follower.configure(followerConfig, ResetMode.kNoResetSafeParameters, PersistMode.kNoPersistParameters);

  }
  ```

Results in 

```
Error at com.revrobotics.spark.SparkBase.configure(SparkBase.java:276): Unhandled exception instantiating robot com.revrobotics.spark.SparkBase java.lang.IllegalStateException: Parameter type mismatch for parameter id
        at com.revrobotics.spark.SparkBase.configure(SparkBase.java:276)
        at frc.robot.subsystems.ExampleSubsystem.<init>(ExampleSubsystem.java:24)
        at frc.robot.RobotContainer.<init>(RobotContainer.java:23)
        at frc.robot.Robot.<init>(Robot.java:28)
        at edu.wpi.first.wpilibj.RobotBase.runRobot(RobotBase.java:301)
        at edu.wpi.first.wpilibj.RobotBase.lambda$startRobot$0(RobotBase.java:418)
        at java.base/java.lang.Thread.run(Thread.java:840)
```

I tried combinations of `ResetMode` and `PersistMode`, but it always seems to happen

**Desktop (please complete the following information if applicable):**
```
WPILib Information:
Project Version: 2025.1.1-beta-1
VS Code Version: 1.94.2
WPILib Extension Version: 2025.1.1-beta-1
C++ Extension Version: 1.22.9
Java Extension Version: 1.36.2024092708
Java Debug Extension Version: 0.58.2024090204
Java Dependencies Extension Version 0.24.0
Java Version: 17
Java Location: C:\Users\Public\wpilib\2025\jdk
Vendor Libraries:
    REVLib (2025.0.0-beta-1)
    WPILib-New-Commands (1.0.0)
```

**Comment by jfabellera** [comment]
this will be fixed in the next beta release

**Comment by jfabellera** [comment]
Also it looks like status signal periods, status signal always-on setting, and MAXMotion parameters will be affected similarly in simulation.

**Comment by jfabellera** [comment]
Did not mean to close this as the fix is not released yet (external PR was linked to this issue).
