### ISSUE TITLE
Shuffleboard immediately crashes on ARM MacOS

### ISSUE THREAD

**Issue by Braykoff** [wpilibsuite/2025Beta#85]
Shuffleboard on an M1 Macbook immediately crashes upon launch. Running MacOS 15.0.

Running the .sh file from the command line gives this error:
```
Exception in thread "main" java.io.IOException: /Users/brendanraykoff/.wpilib/nativecache/osx/universal/bdd0336087563c929fc0f288ab798b4f/libwpiutiljni.dylib could not be loaded from path
	attempted to load for platform /osx/universal/
Last Load Error: 
/Users/brendanraykoff/.wpilib/nativecache/osx/universal/bdd0336087563c929fc0f288ab798b4f/libwpiutiljni.dylib: dlopen(/Users/brendanraykoff/.wpilib/nativecache/osx/universal/bdd0336087563c929fc0f288ab798b4f/libwpiutiljni.dylib, 0x0001): Library not loaded: @loader_path/@rpath/libwpiutil.dylib
  Referenced from: <0F29CE71-5313-394E-B85B-6022D3EE4932> /Users/brendanraykoff/.wpilib/nativecache/osx/universal/bdd0336087563c929fc0f288ab798b4f/libwpiutiljni.dylib
  Reason: tried: '/Users/brendanraykoff/.wpilib/nativecache/osx/universal/bdd0336087563c929fc0f288ab798b4f/@rpath/libwpiutil.dylib' (no such file)

	at edu.wpi.first.util.CombinedRuntimeLoader.loadLibrary(CombinedRuntimeLoader.java:204)
	at edu.wpi.first.util.CombinedRuntimeLoader.loadLibraries(CombinedRuntimeLoader.java:223)
	at edu.wpi.first.shuffleboard.app.Main.main(Main.java:25)
ERROR launching /Users/brendanraykoff/wpilib/2025/tools/Shuffleboard.jar using /Users/brendanraykoff/wpilib/2025/jdk/bin/java
./Shuffleboard.sh: line 11: /bin/java: No such file or directory
ERROR launching /Users/brendanraykoff/wpilib/2025/tools/Shuffleboard.jar using 
Exception in thread "main" java.io.IOException: /Users/brendanraykoff/.wpilib/nativecache/osx/universal/bdd0336087563c929fc0f288ab798b4f/libwpiutiljni.dylib could not be loaded from path
	attempted to load for platform /osx/universal/
Last Load Error: 
/Users/brendanraykoff/.wpilib/nativecache/osx/universal/bdd0336087563c929fc0f288ab798b4f/libwpiutiljni.dylib: dlopen(/Users/brendanraykoff/.wpilib/nativecache/osx/universal/bdd0336087563c929fc0f288ab798b4f/libwpiutiljni.dylib, 0x0001): Library not loaded: @loader_path/@rpath/libwpiutil.dylib
  Referenced from: <0F29CE71-5313-394E-B85B-6022D3EE4932> /Users/brendanraykoff/.wpilib/nativecache/osx/universal/bdd0336087563c929fc0f288ab798b4f/libwpiutiljni.dylib
  Reason: tried: '/Users/brendanraykoff/.wpilib/nativecache/osx/universal/bdd0336087563c929fc0f288ab798b4f/@rpath/libwpiutil.dylib' (no such file)

	at edu.wpi.first.util.CombinedRuntimeLoader.loadLibrary(CombinedRuntimeLoader.java:204)
	at edu.wpi.first.util.CombinedRuntimeLoader.loadLibraries(CombinedRuntimeLoader.java:223)
	at edu.wpi.first.shuffleboard.app.Main.main(Main.java:25)
ERROR launching /Users/brendanraykoff/wpilib/2025/tools/Shuffleboard.jar using java from path: /usr/bin/java
``` 

I have confirmed that this file does exist:
```
/Users/brendanraykoff/.wpilib/nativecache/osx/universal/bdd0336087563c929fc0f288ab798b4f/libwpiutiljni.dylib
```

Running from the VSCode wpilib plugin or the .jar file crashes silently without any output.

**Comment by ThadHouse** [comment]
This was broken in beta 1 but should be fixed at least by beta 3. Are you running beta 3?

**Comment by Braykoff** [comment]
@ThadHouse Yes, I had beta 1 but recently installed beta 3. Should I try to uninstall and reinstall it?

**Comment by ThadHouse** [comment]
Might be worth a shot. This should be fixed by https://github.com/wpilibsuite/shuffleboard/commit/4703aecda44891838e95198c7076c710a6e0125a

**Comment by Braykoff** [comment]
@ThadHouse For some reason a fresh install worked. Thanks!
